### ISSUE TITLE
Missing "=" in documentatiopn

### ISSUE THREAD

**Issue by xjtang** [ceholden/yatsm#24]
In the documentation of Batch Interface, where you give the example of running on Sun Grid Engine, to specify the ethernet speed of the node the option should be -l eth_speed=10. The '=' sign is missing.

**Comment by ceholden** [comment]
Thanks Xiaojing -- nice catch. Good to see someone referencing the documentation and thanks for the report on Github.

Fix should be added to RST document and change is reflected in HTML pushed to gh-pages branch
