### ISSUE TITLE
YATSM >100% CPU utilization with conda

### ISSUE THREAD

**Issue by ceholden** [ceholden/yatsm#51]
Looks like the NumPy included in `conda` can do multithreaded computation for linear algebra routines by linking to OpenBLAS. You can disable this by setting `OPENBLAS_NUM_THREADS=1` as an environment variable, but having all my jobs killed by our cluster's process reaper gave me quite the fright before I found the solution to turning it off!

If we linked against the Intel MKL, we'd also have `MKL_NUM_THREADS` to set.

Proposed solutions:

1. Document it and hope people find it
2. By default, have `yatsm` set the environment variables for multiprocessing to just use one thread. Use some `--num_threads` optional argument in the YATSM cli to turn multiprocessing on.

I'm actually in favor of option 2, but it seems pretty oppressive. Any thoughts @valpasq or @bullocke ?

**Comment by parevalo** [comment]
I think option two makes a lot more sense. Better to go with the safe option and give an option to override it if necessary, no?
________________________________

**Comment by ceholden** [comment]
Ignore the previous reference to a commit. I had the wrong issue number

**Comment by ceholden** [comment]
Commit 6bf7371cb5afaa99a8ef6faee18b9cdbe09ac57c doesn't solve the problem. The idea is right, but it looks like we need to set the environment variables BEFORE `numpy` is ever imported.

This means that we need to import `numpy` even after we load all of the CLI program entry points (e.g., `map`, `line`, `train`, etc.). This could be a whole lot of work that makes things very messy...
