### ISSUE TITLE
Phenology fit error

### ISSUE THREAD

**Issue by ceholden** [ceholden/yatsm#54]
Pulled updated repository yesterday (currently up to date). Tried running YATSM with phenology enabled. A good number of lines process with no issue, but eventually the following error occurs:
```
  File "/usr3/graduate/valpasq/Documents/yatsm/yatsm/phenology.py", line 309, in fit
    self.q_min, self.q_max)
  File "/usr3/graduate/valpasq/Documents/yatsm/yatsm/phenology.py", line 241, in _fit_record
    pad_start = np.arange(1, yeardoy[:, 1].min() + 1)
  File "/project/earth/packages/Python-2.7.5/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity 
```

````yatsm_*.o*```` logfiles located in ```/projectnb/landsat/projects/Massachusetts/```
Verbose turned on to help ID which lines caused the error.

**Comment by ceholden** [comment]
@valpasq try the fix pushed to the `issue54` branch. What looks to be happening is that after scaling the EVI to 0 - 1 range, all of the values came out as NaN. When these are masked out, `yeardoy` is 0-length, hence the exception.

This marks the second time errors related to unusual EVI timeseries crept up. I've run the phenology code on 3-4 stacks and never encountered the issues seen in this `p012r031` dataset. Should be a good thing to include some of these troublemaking pixels in a test dataset.

**Comment by valpasq** [comment]
Tried the fix pushed to the ```issue54``` branch. 

New error on same line:
```  
File "/usr3/graduate/valpasq/Documents/yatsm/yatsm/phenology.py", line 237, in _fit_record
    logger.debug('No valid EVI in segment -- skipping')
NameError: global name 'logger' is not defined
```

Did I miss a package import somewhere?

**Comment by ceholden** [comment]
Whooops -- I guess there wasn't a logger defined. At least we know that the if statement that aborts if 100% of EVI is NaN was triggered.

Try again? I'm testing on a line -- 1206 -- myself but it is taking a while to get to the offending column.

**Comment by valpasq** [comment]
Success!

```
13:44:35:DEBUG:130:line.line:Running line 2702
13:44:36:DEBUG:158:reader.read_line:Read in Y from cache file
14:03:43:DEBUG:240:phenology._fit_record:No valid EVI in segment -- skipping
14:03:44:DEBUG:240:phenology._fit_record:No valid EVI in segment -- skipping
14:03:44:DEBUG:240:phenology._fit_record:No valid EVI in segment -- skipping
14:09:28:DEBUG:194:line.line:    Saving YATSM output to /projectnb/landsat/projects/Massachusetts/p012r031/images/YATSM/yatsm_r2702.npz
14:09:28:DEBUG:201:line.line:Line 2702 took 1492.50471401s to run
```

**Comment by ceholden** [comment]
Great. I want to track down what data are causing the NaN scaled EVI to add as a test, but otherwise it seems ready to merge into master. 

Tracking down the column requires some additional debugging to be added in so I'll try it on own next week.
