### ISSUE TITLE
Error using list of max/min values for non-masked data

### ISSUE THREAD

**Issue by valpasq** [ceholden/yatsm#59]
Tried to enter a list of max/min values for individual bands in my config file:
```
    # Valid range of non-mask band data
    # specify 1 range for all bands, or specify ranges for each band
    min_values: [0, 0, 0, 0, 0, 0, 0, 0, -2000, -5000]
    max_values: [10000, 10000, 10000, 10000, 10000, 10000, 10000, 22000, 4500, 2000] 
```

Got this error about "ambiguous argument types":
```  
File "/usr3/graduate/valpasq/Documents/yatsm/yatsm/cli/line.py", line 150, in line
    cfg['dataset']['max_values']).astype(bool)
  File "yatsm/_cyprep.pyx", line 22, in yatsm._cyprep.__pyx_fused_cpdef (yatsm/_cyprep.c:2945)
TypeError: Function call with ambiguous argument types
```

I am doing something wrong with the syntax?

The yaml file I'm using is here: ```/projectnb/landsat/projects/Massachusetts/p012r031/p012r031_config.yaml```

**Comment by ceholden** [comment]
The Cython function in `_cyprep` only works on integer typed `np.ndarrays` but the configuration parser never changed the type from a `list`.

Fixed in last commit.
