### ISSUE TITLE
Expose "keep_regularized" argument for refit

### ISSUE THREAD

**Issue by valpasq** [ceholden/yatsm#74]
Need to expose ```keep_regularized``` argument for refit:

 ```keep_regularized = TRUE```
If lasso regression coefficient is fit to ```0``` in change detection stage, don't fit in refit stage.

 ```keep_regularized = FALSE```
Refit all coefficients in refit stage.

**Comment by ceholden** [comment]
What do you think about renaming it to something along the lines of `stay_regularized` instead? I wrote the keyword argument `keep_regularized` and it even confuses me sometimes as to what that means (i.e., "keep" meaning retain the regularized coefficients or do we keep with the regularization that happened?).

**Comment by valpasq** [comment]
Yes! I like ```stay_regularized``` much better since we want the coefficients that were regularized to stay regularized, as opposed to keeping the coefficients themselves.

**Comment by ceholden** [comment]
Implemented in commit referenced above.

`refit_record` function will retain `keep_regularized` kwarg for compatibility, but you can specify the behavior using `stay_regularized` in the config file. Just like the prefix, specify a list of True/False per refit method.
