### ISSUE TITLE
CCDCesque: Use list of values for min_rmse

### ISSUE THREAD

**Issue by valpasq** [ceholden/yatsm#75]
We might expect different bands to vary in their RMSE due to differences in scaling. Therefore,
```min_rmse``` hyperparameter for ```CCDCesque``` should accept either (a) a single value that will be applied to all bands (currently implemented) or (b) a list of values for each band, similar to how ```min_values```/```max_values``` for bands is currently structured.

**Comment by ceholden** [comment]
Implemented suggestion in last commit. Given an example of using 7 (no-mask) bands, parameterize as follows:
``` yaml
min_rmse: 100
```
or
```yaml
min_rmse: [100, 100, 100, 100, 100, 100, 100]
```

Seems to work [as using an array of 7 "100" values passes the same test as using `min_rmse=100`](https://github.com/ceholden/yatsm/commit/bf4c49c0e31ede581bf68e40315d20652e40ff8d#diff-2e7f3538d89099475703b60ba923f956R17).
