### ISSUE TITLE
yatsm train cannot find 'design info'

### ISSUE THREAD

**Issue by parevalo** [ceholden/yatsm#80]
I am trying to train a classifier but getting the following error:

```python
Traceback (most recent call last):
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/bin/yatsm", line 9, in <module>
    load_entry_point('yatsm==0.5.5', 'console_scripts', 'yatsm')()
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/yatsm/cli/train.py", line 76, in train
    attrs = find_result_attributes(cfg)
  File "/projectnb/landsat/users/parevalo/yatsm5_venv/lib/python2.7/site-packages/yatsm/cli/train.py", line 181, in find_result_attributes
    attrs.keys())
AttributeError: Could not find following attributes in results: ['design_info']
```
* I'm using yatsm v0.5.5
* Config files in: /projectnb/landsat/projects/Colombia/images/007058/Results/FIT1
* The command I ran is in Train.sh  

I think it's all due to change in structure of the result files, because this issue wasn't present in v0.5.3. Also, I think you may have fixed it already in the dev version (cfe6451) and you even have a test for training now, but wanted to make sure because I want to use the more "stable" version at the moment. Before I had this issue, I had gotten the latest dev version but decided to go back to the latest release because there was something incompatible I didn't really want to deal with.

**Comment by ceholden** [comment]
I think you tracked down the origin of the problem correctly, but I'm confused what you'd like me to do if you'd like my help. There seem to be a few possibilities:

1. Use a version of YATSM that is working
    * Seems like the commit you referenced would work, but so I can't test because the pickled predictors referenced in the config file you pointed to don't exist anymore. Without them, I can't parse the configuration file properly
2. Edit the training script to use the correct metadata attribute
    * Two lines of edit
3. Edit your results files to work with the version you want
    * ~15 lines of code to open, upgrade result file metadata, save the result back

I really want to release `v0.6.0` as the next release instead of some additional bugfix to `v0.5.*`. When that's out I'm basically going to forget the `v0.5.*` releases ever happened. There might eventually be some "upgrade my results" script, but that'll likely be more to upgrade to different file formats (e.g., HDF5).

Seems like #2 is the way to go -- can you try with the edits shown in this diff?:
https://github.com/ceholden/yatsm/commit/cfe64510f020ff3d91f35b64519eca8fcd6d0328#diff-9193483859cc755620856f23e168eb90L173

Cheers

**Comment by parevalo** [comment]
Ahh okay, I just wanted to make sure I was getting it right and I knew
you'd provide a sensible suggestion. I'm going to try #2 and I will let you
know how it goes. As for the pickles, I had switched to the master branch
in order to install it in a separate virtual environment after I sent the
issue, so that's probably why they were gone. Thank you.

**Comment by ceholden** [comment]
Great -- hope that works but we can investigate in person tomorrow if that doesn't work.

Apologies for the wacky version instabilities. I'll try to release a new version on Wednesday after our meeting that'll basically act as a feature freeze to base bug fixes on top of.

**Comment by parevalo** [comment]
Seems to work!
