### ISSUE TITLE
BUG: corner cases

### ISSUE THREAD

**Issue by ceholden** [ceholden/yatsm#88]
1. In very short time series (e.g., edge of images), `CCDCesque` implementation can sometimes not estimate regression models for the non-test indices.
    * If we train a model but cannot monitor for even a single observation, `self._update_model()` will not be called because it is [in the monitoring block](https://github.com/ceholden/yatsm/blob/master/yatsm/algorithms/ccdc.py#L227)
    * Fix: run `self._update_model` as soon as the training stage finishes so that all `p` features may be estimated
2. Again, in very short time series when `n = p`, the RLM code will throw a `DGELSD` error
    * When `n = p`, the residuals are `resid < epsilon` (i.e., 0)
    * When all residuals are 0, the initial scale estimate is also 0
    * Fix: return when the initial scale estimate is 0

**Comment by parevalo** [comment]
Wondering if the fix is as simple as the changes I made, so I referenced the issue in the commit I made to my own repository. I ran the pixel with no errors, BTW.

**Comment by ceholden** [comment]
Awesome! I have a two nitpicks I'd like you to address and then we could merge it into the main repo. I'll comment on your commit with them.

It would also be good if you could separate the two fixes into two different commits. Again, a nitpick but it is good to isolate changes, especially when we're changing the algorithms
